import sys
from playwright.sync_api import sync_playwright
OUT = sys.argv[1]; errs = []; warns = []; ok = lambda c, m: print(('PASS ' if c else 'FAIL ') + m)
with sync_playwright() as p:
    b = p.firefox.launch(headless=True); pg = b.new_page(viewport={'width': 1280, 'height': 720})
    pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.on('console', lambda m: (warns.append(m.text) if '[anim]' in m.text else errs.append(m.text) if m.type == 'error' else None))
    pg.goto('http://127.0.0.1:5173/')
    pg.wait_for_function("window.__rs && __rs.Models.ready && !document.getElementById('menu').classList.contains('hidden')", timeout=120000)
    pg.click('#btnDeploy'); pg.wait_for_function("__rs.Game.state === 'play' && __rs.Player.alive", timeout=30000); pg.wait_for_timeout(1500)
    pg.evaluate("""() => { const M = __rs.MAP; for (let k = 0; k < 400; k++){ const p = M.randomOpen();
        if (!M.boxes.some(b => b.x0 - 3.5 < p.x && b.x1 + 3.5 > p.x && b.z0 - 3.5 < p.z && b.z1 + 3.5 > p.z && b.y1 > .05)){ __rs.Player.pos.set(p.x, 0.05, p.z); window.__home = p; break; } } if (!window.__home) window.__home = { x: __rs.Player.pos.x, z: __rs.Player.pos.z };
        __rs.Game.local.spawnProt = 1e9; __rs.Input.enabled = true;
        for (const a of __rs.Game.actors) if (a.isBot){ a.alive = false; a.respawnT = 1e9; a.pos.set(0, -50, 0); } }""")
    home = lambda: pg.evaluate("__rs.Player.pos.set(__home.x, 0.05, __home.z); __rs.Player.vel.set(0,0,0)")
    an = lambda: pg.evaluate("({ kind: __rs.Game.local.anim.kind, frozen: __rs.Game.local.anim.frozen, on: [...__rs.Game.local.anim.active].filter(n => __rs.Game.local.anim.w[n] > .25), reload: __rs.Game.local.anim.reloadClip })")
    pg.keyboard.press('v'); pg.wait_for_timeout(800); pg.keyboard.press('2'); pg.wait_for_timeout(900)
    a = an(); ok(a['kind'] == 'pistol' and a['on'] == ['pistol_idle'], 'pistol idle %s' % a); pg.screenshot(path=OUT + '/ps_idle.png')
    pg.keyboard.down('w'); pg.wait_for_timeout(900); a = an(); pg.screenshot(path=OUT + '/ps_run.png'); pg.keyboard.up('w'); pg.wait_for_timeout(500)
    ok(any(n.startswith('pistol_run_f') or n.startswith('pistol_walk_f') for n in a['on']) and not a['frozen'], 'pistol forward %s' % a)
    home(); pg.keyboard.down('d'); pg.wait_for_timeout(900); a = an(); pg.keyboard.up('d'); pg.wait_for_timeout(500)
    ok('pistol_walk_r' in a['on'], 'pistol strafe right %s' % a)
    home(); pg.keyboard.down('s'); pg.wait_for_timeout(900); a = an(); pg.keyboard.up('s'); pg.wait_for_timeout(500)
    ok(any(n.startswith(('pistol_run_b', 'pistol_walk_b')) for n in a['on']), 'pistol backward %s' % a)
    home(); pg.wait_for_function("__rs.Player.onGround", timeout=4000); pg.keyboard.press('Space'); pg.wait_for_timeout(250); a = an()
    ok('pistol_jump' in a['on'], 'pistol standing jump plays its airborne section %s' % a); pg.wait_for_timeout(900)
    pg.keyboard.press('c'); pg.wait_for_timeout(700); a = an()
    ok('pistol_crouch_idle' in a['on'], 'pistol crouch idle = kneeling idle %s' % a)
    home(); pg.keyboard.down('w'); pg.wait_for_timeout(700); a = an(); pg.keyboard.up('w')
    ok(a['frozen'] == 'pistol_crouch_f', 'pistol crouch-walk: missing, pose held %s' % a)
    pg.keyboard.press('Space'); pg.wait_for_timeout(500)
    pg.evaluate("__rs.Wep.ammo[__rs.Wep.def.id].mag = 2"); pg.keyboard.press('r'); pg.wait_for_timeout(600); a = an()
    ok(a['reload'] is None, 'pistol reload: missing, nothing substituted %s' % a)
    pg.wait_for_function("__rs.Wep.reloadT <= 0", timeout=6000)
    pg.keyboard.press('3'); pg.wait_for_timeout(900); a = an()
    ok(a['kind'] == 'none' and 'unarmed_idle' in a['on'], 'grenade in hand: unarmed idle clip %s' % a)
    b.close()
print('anim warnings:', sorted(set(w.split('"')[1] for w in warns if '"' in w)))
print('errors', errs[:5])
